# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compare_files <- function(expected, test) {
    .Call('vdiffr_compare_files', PACKAGE = 'vdiffr', expected, test)
}

